### ISSUE TITLE
<AbsoluteGrid> does not render inside react-bootstrap <Tab>

### ISSUE THREAD

**Issue by gbmhunter** [jrowny/react-absolute-grid#17]
For some reason, `<AbsoluteGrid />` does not render inside of a [react-bootstrap](https://react-bootstrap.github.io/components.html#tabs) `<Tab>` element.

e.g. This works

````
<AbsoluteGrid items={items} />
````

But this doesn't:

````
import { Tabs, Tab } from 'react-bootstrap';
<Tab eventKey={0} title="Calculators">
   <AbsoluteGrid items={items} />
</Tab>
````

And by render, I don't mean a styling issue, the DOM for `<AbsoluteGrid>` does not even get created. Anything else inside the `<Tab>` renders correctly.

**Comment by gbmhunter** [comment]
Does it have something todo with `this.state.layoutWidth`?

I see this in `class AbsoluteGrid`:
````
if(!this.state.layoutWidth || !this.props.items.length){
      return <div></div>;
}
````

**Comment by jrowny** [comment]
Yea, I think what's happening is layout.width gets calculated to 0 and therefore doesn't render. You could test this by resizing the window frame with responsive=true, if it shows up, that's the problem. 

Because the layout is absolute, we must know the actual width we have to render in. I could expose a method to recalculate that but let me noodle on a cleaner more automagic way to do that.

**Comment by gbmhunter** [comment]
layout.width was 0, and setting `responsive={true}` didn't fix things. Then I noticed the following code blocking all re-renders:

````
onResize = () => {
    if (!this.running) {
    ...
````

I notice this has been fixed in the latest version, however I can't use this library as a normal npm module as I can't compile .jsx files within the `node_modules` folder (are you ever going to provide compiled .js files? Many react libraries do, and it makes them really easy to use).

**Comment by jrowny** [comment]
It should be compiled and linked properly to the dist dir which us in
gitignore, maybe I didn't npm publish correctly. I

**Comment by gbmhunter** [comment]
Oh right, so it should provide compiled libraries? If so, I will pull the latest version and try again...

**Comment by jrowny** [comment]
It should, if not let me know

**Comment by gbmhunter** [comment]
Oh I had another thought, it still will have ES6 syntax won't it? That might be the problem, as I don't run babel on anything in the node_modules folder either.

**Comment by jrowny** [comment]
No, it should be run through bablify.

**Comment by okonet** [comment]
It doesn ATM. See #18 for detailed info.

**Comment by newsiberian** [comment]
Hello, I've faced with similar problem. I'm trying to build the exact copy from your `readme`, but even in that case items not render for me. In my case seems like `layoutWidth === 0`, so every time this `if(!this.state.layoutWidth || !this.props.items.length){` is `true`
![absolute-grid](https://cloud.githubusercontent.com/assets/11130487/13528149/055363a8-e236-11e5-8297-3ed57b25e0b8.png)
Any idea?
