### ISSUE TITLE
How to fit AbsoluteGrid in container?

### ISSUE THREAD

**Issue by austinmao** [jrowny/react-absolute-grid#19]
Specifying itemWidth and itemHeight that is bigger than the containing div will create overflow. Unfortunately, I do not always know the container size. Is there a way to make sure that this component does not overflow its containing div?

**Comment by jrowny** [comment]
You could try adding responsive=true, but that only listens to resizes on the browser window. Unfortunately for an absolute layout to work we must know the width. We might be able to expose a method or handler you could call to manually recalculate the layout.

**Comment by austinmao** [comment]
Thank you. FYI I am using this to shortcut my way there: https://github.com/digidem/react-dimensions
Might I also suggest options to do different types of scaling/fitting? i.e., Scale fill, aspect fit, aspect fill, etc.
