### ISSUE TITLE
Cannot find babelify

### ISSUE THREAD

**Issue by lastlegion** [jrowny/react-absolute-grid#20]
I am trying to use this in one of my projects. However I get this error:
Cannot find module 'babelify' from '<my_project_directory>/node_modules/react-absolute-grid'

When I run browserify from Grunt.

**Comment by lastlegion** [comment]
Was able to resolve it by removing .babelrc

**Comment by okonet** [comment]
I'm not familiar with browserify, but you don't need to compile this module if you install from npm since #16 has been merged. I assume browserify is being too smart and treats existnace of `.babelrc` as a flag to compile it. Probably a solution would be to remove `.babelrc` from npm.
