### ISSUE TITLE
IE 10 drag and drop support

### ISSUE THREAD

**Issue by mheiber** [jrowny/react-absolute-grid#23]
Beautiful work! I'm hoping to use this for a project, but IE 10 support is a hard requirement. The Readme says that IE 10 support is coming soon - how soon? I'd be happy to help.

**Comment by jrowny** [comment]
The main issue with IE10 is that `pointer-events: none` doesn't work, which is what we use to allow the mouse to hover on other elements. The work around is to flip "display" to none on the element, and then flip it back after finding the target. IE 10 won't render the none, but allows you to use elementFromPoint. 

```
if (navigator.appVersion && navigator.appVersion.indexOf("MSIE 10") !== -1){
   draggingElement.style.display = "none";
   //find the target
   draggingElement.style.display = "block";
}
```

This would be done around Line 43 of drag manager: https://github.com/jrowny/react-absolute-grid/blob/master/lib/DragManager.js#L43

It's an ugly hack, but that's IE10. I don't have the time to support IE10 right now, but if you'd like to make a PR, I'll be glad to accept it.

**Comment by mheiber** [comment]
Thanks for getting back to me about this issue!
