### ISSUE TITLE
Babel 6.x support?

### ISSUE THREAD

**Issue by nadilas** [jrowny/react-absolute-grid#28]
Hello there,

I'm facing the following issue when using babelify transform within our browserify gulp task:

`ReferenceError: [BABEL] /path/to/node_modules/react-absolute-grid/lib/AbsoluteGrid.jsx: Using removed Babel 5 option: /path/to/node_modules/react-absolute-grid/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets`

We are using the following package versions:

> babelify: v7.3.0
> babel-core: v6.0.14
> browserify: v13.0.1

No matter how I configure my gulp task or the project, the same error error persists.

Are you planning on supporting the 6.x.x version of babel? Or should I just use the /dist/index.js instead of letting the grid build along with my project?

Thanks in advance!

**Comment by bjoerge** [comment]
This should also be fixed by #26 which is merged, but not yet released.

**Comment by jrowny** [comment]
fixed in `3.0.0`
