### ISSUE TITLE
React 0.15.x support ?

### ISSUE THREAD

**Issue by M3lkior** [jrowny/react-absolute-grid#29]
Hi,

Your component seems great.Good work !

Does it support React 0.15 ?

**Comment by jrowny** [comment]
I haven't tested, but it should.

**Comment by nethermead** [comment]
I'm trying this now and one issue is peerDependencies in package.json:

"peerDependencies": {
    "react": "^0.14.0"
  },

**Comment by jrowny** [comment]
ah, you might be able to just upgrade NPM and get away with ignoring it for
now, but I'll see if I can't get a proper test/update to 0.15 done this
week. PRs welcome!

**Comment by el1f** [comment]
Was anybody able to test if the component works well with 0.15.x?

**Comment by Gorb** [comment]
Implemented this in my react@15.3.2 project but it doesn't appear to be working. Unsure if it's due to my unfamiliarity with this module, though:

> warning.js:36 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `QuizView`.
> 
> invariant.js:38 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `QuizView`.

QuizView is the page-level component.

```
var sampleItems = [
  {key: 1, name: 'Test', sort: 0, filtered: 0},
  {key: 2, name: 'Test 1', sort: 1, filtered: 0}
];

<AbsoluteGrid items={sampleItems} displayObject={(<AbsoluteGridView />)} />
```

AbsoluteGridView was taken from the sample displayObject class (I've tried with and without props):

```
var React = window.React = require("react");

var AbsoluteGridView = React.createClass({
  getInitialState:function() {
    return {  };
  },

  componentDidMount:function() {
  },

  render:function() {
    const { item, index, itemsLength } = this.props;
    return <div>Item { index } of { itemsLength }: { item.name }</div>;
  }
});

module.exports = AbsoluteGridView;
```

**Comment by jrowny** [comment]
@Gorb @el1f  @nethermead 

I just pushed a new branch #35 of the component that supports 15.3.x and up but it's using PureComponent now so you must pass it immutable data.

**Comment by jrowny** [comment]
version 3.0.0 is officially released to NPM and it works a little differently, but works great with 15.3 and up.
