### ISSUE TITLE
WebkitTransform capitalization

### ISSUE THREAD

**Issue by fergusg** [jrowny/react-absolute-grid#3]
I have a fleeting glance at your interesting code.  I'm no expert but I see you use WebkitTransform (captial W) - I thought it should be webkitTransform:

https://developer.apple.com/library/safari/documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/Using2Dand3DTransforms/Using2Dand3DTransforms.html#//apple_ref/doc/uid/TP40008032-CH15-SW16

though I suspect I'm misunderstanding how your code works.

**Comment by jrowny** [comment]
@fergusg normally you are correct, but not within React. See the docs here: https://facebook.github.io/react/tips/inline-styles.html
