### ISSUE TITLE
Can't delete a displayObject item without a warning

### ISSUE THREAD

**Issue by mmela** [jrowny/react-absolute-grid#34]
Hi everyone,

First, thanks for the great work.

I can't figure out how to remove an item in the `items` array. I've tried using `splice` for an element and then re-rendering, but I get the warning:
> Warning: setState(...): Can only update a mounted or mounting component

I store the items array in a state (`this.state.imageBlocks`). Every `displayObject` has an `onClick` handler bound to the below mentioned callback `destroyImage` that removes the item and updates the state array.
```
 destroyImage(item) {
    var newBlocks = this.state.imageBlocks, index;
    index = newBlocks.findIndex(i => i.key === item.key);
    newBlocks.splice(index, 1);
    this.setState({imageBlocks: newBlocks});
  },
```

I assume the warning relates to not unbinding `onClick` handler in the `componentDidUnmount` of the `displayObject`. I wasn't able to find a way to unbind that.

Any pointers would be appreciated.

**Comment by jrowny** [comment]
can you try with the new version? thanks!

**Comment by felix-fabrega** [comment]
Hi, I have exactly the same issue. Did you solved it ?

**Comment by mmela** [comment]
Works for me!
