### ISSUE TITLE
Usage with render()?

### ISSUE THREAD

**Issue by ryanthon** [jrowny/react-absolute-grid#37]
Hi,

I'm trying to integrate this component into my project, but I can't get it to render. I've read through the Usage and README, but it doesn't seem to include any examples of how to render the grid inside a component's render() function. I'm using react 15.x

Here's my render function:

```
render: function() {
        const {unit} = this.props;
        const AbsoluteGrid = createAbsoluteGrid(DraggableItem);

        return (
            <div className="tab-pane fade">
                <div className="col-md-12 col-xs-12 text-right edit-organization-field">
                    <button type="button">Add new... </button>
                </div>

                <div className="col-md-12">
                    <AbsoluteGrid items={unit.items}
                                  keyProp="id"
                                  sortProp="displayOrder"
                                  responsive={true}
                                  dragEnabled={true}/>
                </div>
            </div>
        )
    }
```

And here's my DisplayComponent:
```
class DraggableItem extends React.PureComponent {

    render() {
        const {item} = this.props;

        return (
            <div>
                <img src={Utils.getIcon(item.icon, false)} />
                <p  className="icon-heading">{item.name}</p>
            </div>
        );
    }
}
```

Running the project and that page just gives me an empty div where the AbsoluteGrid should be.
However, when making an edit and triggering a re-build, it re-renders the page, and the grid shows (although it's not functional). Is there something I'm doing wrong?

**Comment by jrowny** [comment]
The `const AbsoluteGrid = createAbsoluteGrid(DraggableItem);` should only need to be done once outside of the render, other then that I don't see anything wrong.

**Comment by richessler** [comment]
@jrowny I too am 
```
render() {
    const AbsoluteGrid =  createAbsoluteGrid(RegistryItemCell);
    return(
      <AbsoluteGrid items={this.props.registryTileData}
                    onMove={onMoveDebounced}
                    dragEnabled={true}
                    zoom={zoom}
                    responsive={true}
                    verticalMargin={42}
                    itemWidth={230}
                    itemHeight={409}/>
    )
  }
```

I get an error `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.` Can you advise on the proper way to render the grid when including in a React.Component?

**Comment by jrowny** [comment]
@richessler this component uses composition to create the actual grid component. This composition is done once, by placing it inside the `render()` you're doing it every time it renders. It needs to be somewhere else even outside your component. It's the same idea as when you use `connect()` in Redux... you're composing that component.
