### ISSUE TITLE
Items are rendered on top of each other. How do I fix it?

### ISSUE THREAD

**Issue by exogenesys** [jrowny/react-absolute-grid#39]
Items are stacked on top of each and not aligned in a grid. How do I fix them?

I'm using Semantic UI for React. And I have put it in what's called a [Segment](http://react.semantic-ui.com/elements/segment) which is inside a [Container](http://react.semantic-ui.com/elements/container). I don't think they should cause any problem as removing them doesn't help.

Other than that I'm using JSX and next.js, which probably makes get rendered on the server, which again I think shouldn't be a problem. I guess.

Thanks a lot!

![image](https://user-images.githubusercontent.com/8681754/27158861-e5d6a46a-5186-11e7-8264-fe3185380396.png)

**Comment by willtrking** [comment]
Had the same issue, make sure the set the "key" key in your items, like under the Usage section of the readme.

Can change the name of it with `keyProp` as well
