### ISSUE TITLE
Question: How to fix the max height of the grid

### ISSUE THREAD

**Issue by felix-fabrega** [jrowny/react-absolute-grid#40]
Hi,
I'm looking for a way to fix the height of the grid. For now, I tried to put a height on its container but the grid style render out of the box. I tried to put a fixed size everywhere but nothing worked to make the grid in a fixed sized box with a scollbar.
Can someone indicate me a way to do it ?

Thanks,

**Comment by jrowny** [comment]
If you add `overflow: auto` and `max-height: 1024px` to the container style , it should add a scroll bar and work just fine.
