### ISSUE TITLE
How to filter grid items using radio buttons in a React component?

### ISSUE THREAD

**Issue by ooloth** [jrowny/react-absolute-grid#44]
I'm having trouble wiring up react-absolute-grid using radio buttons within a React component. I tried adapting the demo implementation to a React component, but I may be making some errors along the way. 

Initially, both grid items are rendered, but they are not filtered (i.e. shown/hidden) as I click the radio buttons (even though `this.state.filteredItems` updates with each radio button click).

Here's what I have so far:

```js

import React from 'react'
import createAbsoluteGrid from 'react-absolute-grid'

const items = [
  { key: 1, name: 'Test 1', filtered: false },
  { key: 2, name: 'Test 2', filtered: false }
]

const GridItem = ({ item }) => <p>{item.name}</p>
const AbsoluteGrid = createAbsoluteGrid(GridItem)

class Grid extends React.Component {
  constructor(props) {
    super(props)
    this.state = { filteredItems: items.slice() }
  }

  filterItems = event => {
    let name = event.target.value
    this.setState.filteredItems = this.state.filteredItems.map(item => {
      let isMatched = item.name == name
      item.filtered = !isMatched
      return item
    })
  }

  render() {
    return (
      <div>
        <input onClick={this.filterItems} type="radio" value="Test 1" name="name"/> Test 1
        <input onClick={this.filterItems} type="radio" value="Test 2" name="name"/> Test 2
	<AbsoluteGrid items={this.state.filteredItems} responsive={true} />
      </div>
    )
  }
}

```

Can you let me know what I'm doing wrong?

**Comment by jrowny** [comment]
The way it works is by setting `display: none` to the item, therefore avoiding any DOM work at all. It's possible that you've got some CSS interfering with that?

**Comment by rafaelamsili** [comment]
Hi @jrowny 

I am also trying a similar thing with the drag and drop and it doesn't render after I try to swap the items in the array

`import React from 'react';
import createAbsoluteGrid from 'react-absolute-grid';

const AbsoluteGrid = createAbsoluteGrid(GridItem);
class TileGridList extends React.Component {
    constructor() {
        super();
        this.handleMove = this.handleMove.bind(this);
        this.handleDragEnd = this.handleDragEnd.bind(this);

        var items = [];
        for (var i = 0; i < 16; i++) {
            items.push(<TileItem index={i} key={"app" + i} name={"Application "+i} url={"xyz"}/>);
        }

        this.state = {
            apps: items
        }

    }

    handleDragEnd(){
    }

    handleMove(from,to){
        let items = this.state.apps;
        let fromIdx = items.findIndex(x => x.key === from);
        let toIdx = items.findIndex(x => x.key === to);

        if (fromIdx > -1 && toIdx > -1){
            let temp = items[fromIdx];
            items[fromIdx] =  items[toIdx];
            items[toIdx] =  temp;

            this.setState({apps : items});
        }

    }
    render () {
        return (
            <AbsoluteGrid items={this.state.apps} animation="transform 300ms ease" responsive={true} dragEnabled={true}  onMove={this.handleMove} onDragEnd={this.handleDragEnd} />
        );
    }
}
`

Is there is any way you cans hare the code for draggin you used in your demo?

**Comment by kennyt6** [comment]
@ooloth Did you ever figure this out? I'm trying to implement this grid as well but whenever I filter it blows away the entire grid and then reloads it, its not smooth like their demo. No idea what I'm doing wrong.

**Comment by ooloth** [comment]
@kennyt6 I don't remember! 

In general, I ended up moving on and now prefer customizing my own animations using libraries like `react-spring` and `framer-motion`.
