### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined when calling createAbsoluteGrid()

### ISSUE THREAD

**Issue by rwchampin** [jrowny/react-absolute-grid#46]
TypeError: Cannot read property 'object' of undefined when calling createAbsoluteGrid() for the follwoing 

"dependencies": {
    "jquery-ui-bundle": "^1.12.1",
    "lodash": "^4.17.4",
    "react": "^16.2.0",
    "react-absolute-grid": "^3.0.0",
    "react-dnd": "^2.5.4",
    "react-dnd-html5-backend": "^2.5.4",
    "react-dom": "^16.2.0",
    "react-grid-layout": "^0.16.2",
    "react-gridstack": "^0.1.4",
    "react-scripts": "1.1.0"
  }

The way PropTypes is being imported inside of AbsoluteGrid.jsx no longer works.  I fixing that after changing it to:

import PropTypes from 'prop-types';

But then there are further errors after that has been fixed.

**Comment by shawngmc** [comment]
I'm seeing this same issue too; I really hope there's a workaround, as a like the grid based on the demo...

**Comment by jrowny** [comment]
This should be fixed by version 3.0.1, thanks to #41
