### ISSUE TITLE
Rendering expandable elements

### ISSUE THREAD

**Issue by sartios** [jrowny/react-absolute-grid#48]
Hi,

I work on a use case where I need to sort a few elements that could be expanded. The problem I encountered was that when an element was expanded the expanded content was overflowing behind the next element in the same column.

Initial state

![image](https://user-images.githubusercontent.com/917573/38681988-b19a6856-3e72-11e8-9fc7-f2e315f78a88.png)

Expanded state (with darker blue is the expanded content)

![image](https://user-images.githubusercontent.com/917573/38682235-3f34238c-3e73-11e8-9fc9-379b4aef2a1a.png)

A better behavior would be the following, where the expanded content moves the item down to y-axis

![image](https://user-images.githubusercontent.com/917573/38682604-30fc6756-3e74-11e8-8cac-0e70c0a7b738.png)

**Comment by jrowny** [comment]
I think this is beyond the scope of this project. That use case requires the use of something like masonry or flexbox to do layout. The goal of this project is to be fast by doing our own layout quickly.
